"""behavioural tests for ``docker/family_from_base.py``.

that helper ships INSIDE ``threetears-base`` (see the base Dockerfile) so every
consumer image -- the hub, identity-core, and any future one -- runs the same
family-version check from one source instead of a copy per repo. these tests
live here for the same reason: beside the code, not duplicated beside each
caller.

invocation:

    uv run pytest tests/test_family_from_base_script.py -v
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "docker"))

from family_from_base import strip_family_requirements  # noqa: E402


def _preceded_by_a_requirement(lines: list[str], index: int) -> bool:
    """walk back over continuations to find the requirement this hash belongs to.

    :param lines: the rendered requirements file, split into lines
    :ptype lines: list[str]
    :param index: index of the ``--hash=`` line being attributed
    :ptype index: int
    :return: whether a requirement line precedes this hash
    :rtype: bool
    """
    found = False
    for candidate in reversed(lines[:index]):
        stripped = candidate.strip()
        if not stripped or stripped.startswith("#"):
            continue
        found = not stripped.startswith("--hash=")
        break
    return found


class TestStrippingAFamilyRequirementTakesItsHashLines:
    """``uv export`` emits ``--hash=`` continuation lines under each requirement.

    Dropping the requirement and leaving its continuations behind produces a
    file whose first orphan line uv refuses with ``Unexpected '-', expected
    '-c', '-e', '-r' or the start of a requirement``, which fails the image
    build at ``uv pip install`` -- after a successful export, so the export
    itself looks fine.
    """

    _EXPORTED = (
        "# This file was autogenerated by uv\n"
        "3tears==0.23.8 \\\n"
        "    --hash=sha256:aaaa \\\n"
        "    --hash=sha256:bbbb\n"
        "    # via aibots\n"
        "httpx==0.28.1 \\\n"
        "    --hash=sha256:cccc\n"
        "    # via aibots\n"
    )

    def test_no_orphaned_hash_line_survives(self) -> None:
        """a dropped requirement takes its continuation lines with it.

        :return: nothing
        :rtype: None
        """
        kept, _ = strip_family_requirements(self._EXPORTED)

        orphans = [
            line
            for index, line in enumerate(kept.splitlines())
            if line.lstrip().startswith("--hash=") and not _preceded_by_a_requirement(kept.splitlines(), index)
        ]
        assert orphans == []

    def test_the_family_requirement_is_gone(self) -> None:
        """the family line is removed from the kept text and reported as dropped.

        :return: nothing
        :rtype: None
        """
        kept, dropped = strip_family_requirements(self._EXPORTED)

        assert "3tears==0.23.8" not in kept
        assert any("3tears==0.23.8" in line for line in dropped)

    def test_a_non_family_requirement_keeps_its_hashes(self) -> None:
        """stripping too much is the same build failure from the other side.

        :return: nothing
        :rtype: None
        """
        kept, _ = strip_family_requirements(self._EXPORTED)

        assert "httpx==0.28.1 \\" in kept
        assert "--hash=sha256:cccc" in kept

    def test_the_result_has_no_dangling_continuation_marker(self) -> None:
        """a kept line ending in a backslash must be followed by something.

        :return: nothing
        :rtype: None
        """
        lines = strip_family_requirements(self._EXPORTED)[0].splitlines()

        assert not (lines and lines[-1].rstrip().endswith("\\"))


class TestTheHelperShipsInTheBaseImage:
    """the base Dockerfile must actually carry the helper consumers invoke.

    the hub and identity Dockerfiles run ``/opt/threetears/family_from_base.py``
    and copy nothing themselves; if the base stopped shipping it, both builds
    break at once and the message is a bare "No such file or directory".
    """

    def test_the_base_dockerfile_copies_the_helper(self) -> None:
        """the base image places the helper at the path consumers invoke.

        :return: nothing
        :rtype: None
        """
        text = (_REPO_ROOT / "docker" / "Dockerfile").read_text(encoding="utf-8")

        assert "docker/family_from_base.py /opt/threetears/family_from_base.py" in text
